UCLA scl 1.0
# Created : 07/05/2025 12:20:15

NumRows : 199

CoreRow Horizontal
	Coordinate   : 32
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 40
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 48
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 56
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 64
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 72
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 80
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 88
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 96
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 104
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 112
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 120
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 128
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 136
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 144
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 152
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 160
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 168
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 176
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 184
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 192
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 200
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 208
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 216
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 224
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 232
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 240
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 248
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 256
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 264
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 272
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 280
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 288
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 296
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 304
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 312
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 320
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 328
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 336
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 344
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 352
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 360
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 368
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 376
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 384
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 392
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 400
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 408
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 416
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 424
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 432
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 440
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 448
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 456
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 464
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 472
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 480
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 488
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 496
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 504
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 512
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 520
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 528
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 536
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 544
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 552
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 560
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 568
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 576
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 584
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 592
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 600
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 608
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 616
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 624
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 632
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 640
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 648
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 656
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 664
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 672
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 680
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 688
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 696
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 704
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 712
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 720
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 728
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 736
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 744
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 752
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 760
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 768
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 776
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 784
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 792
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 800
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 808
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 816
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 824
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 832
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 840
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 848
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 856
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 864
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 872
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 880
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 888
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 896
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 904
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 912
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 920
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 928
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 936
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 944
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 952
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 960
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 968
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 976
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 984
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 992
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1000
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1008
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1016
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1024
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1032
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1040
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1048
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1056
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1064
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1072
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1080
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1088
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1096
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1104
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1112
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1120
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1128
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1136
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1144
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1152
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1160
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1168
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1176
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1184
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1192
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1200
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1208
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1216
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1224
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1232
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1240
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1248
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1256
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1264
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1272
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1280
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1288
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1296
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1304
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1312
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1320
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1328
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1336
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1344
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1352
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1360
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1368
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1376
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1384
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1392
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1400
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1408
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1416
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1424
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1432
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1440
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1448
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1456
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1464
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1472
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1480
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1488
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1496
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1504
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1512
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1520
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1528
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1536
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1544
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1552
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1560
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1568
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1576
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1584
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1592
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1600
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1608
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
CoreRow Horizontal
	Coordinate   : 1616
	Height       : 8
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 12	NumSites : 1181
End
